# Finding mean and std in transforms.Normalize in Pytorch

First we import all the necessary tools

In [1]:
import os
from torchvision import datasets, transforms
import numpy as np

In [2]:
train_transform = transforms.Compose([transforms.ToTensor()])

In [3]:
# CIFAR10
train_data = datasets.CIFAR10('data', train=True,
                              download=True, transform=train_transform)
print(train_data.data.shape)

Files already downloaded and verified
(50000, 32, 32, 3)


In [4]:
print(train_data.data.mean(axis=(0,1,2))/255)
print(train_data.data.std(axis=(0,1,2))/255)

[0.49139968 0.48215841 0.44653091]
[0.24703223 0.24348513 0.26158784]


In [5]:
# CIFAR100
train_data = datasets.CIFAR100('data', train=True, download=True, transform=train_transform)
print(train_data.data.shape)

Files already downloaded and verified
(50000, 32, 32, 3)


In [6]:
print(train_data.data.mean(axis=(0,1,2))/255)
print(train_data.data.std(axis=(0,1,2))/255)

[0.50707516 0.48654887 0.44091784]
[0.26733429 0.25643846 0.27615047]


In [7]:
# MNIST
train_data = datasets.MNIST(root='../data/', train=True, download=True, transform=train_transform)
print(list(train_data.data.size()))

[60000, 28, 28]


In [8]:
print(train_data.data.float().mean(axis=(0,1,2))/255)
print(train_data.data.float().std(axis=(0,1,2))/255)

tensor(0.1307)
tensor(0.3081)
